version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5001:5000"
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  mongodb_data: